server:
  port: 8888   # web应用服务端口
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hsmovie?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true  #mysql连接测试报错加这段代码 &allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .ftl # 模版文件后缀名
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/